version: '3'

services:
  mysql:
    image: tutum/mysql:5.6
    container_name: shopware_db
    environment:
     MYSQL_USER: '${MYSQL_USER}'
     MYSQL_PASS: '${MYSQL_PASSWORD}'
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'

  pma:
    container_name: shopware_pma
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
     - '8080:80'

  shop:
    container_name: shopware
    image: dnhsoft/shopware:5.5.6
    volumes:
      - ./media:/shopware/media
      - ./plugins:/shopware/custom/plugins
    ports:
      - '10000:80'
    links:
      - 'mysql:db'
